export const MAFIA_TEXT = {
  phases: {
    idle: 'في الانتظار',
    lobby: 'الصالة - اكتب !انضم للانضمام',
    roleReveal: 'تم توزيع الأدوار',
    night: 'الليل',
    day: 'النهار',
    voting: 'مرحلة التصويت',
    voteResult: 'نتيجة التصويت',
    gameOver: 'انتهت اللعبة',
  },
  roles: {
    mafia: 'مافيا',
    doctor: 'طبيب',
    detective: 'محقق',
    citizen: 'مواطن',
  },
  actions: {
    join: '!انضم',
    kill: '!اقتل <اسم>',
    heal: '!اشف <اسم>',
    investigate: '!تحقق <اسم>',
    vote: '!صوت <اسم>',
  },
  labels: {
    remainingTime: 'الوقت المتبقي',
    timer: 'المؤقت',
    eliminatedPlayers: 'اللاعبين المستبعدون',
    noNightAction: 'لا يوجد إجراء ليلي',
    actionConfirmed: 'تم تنفيذ الإجراء',
    nightActionsTitle: 'إجراءات الليل',
    nightSecretCommands: 'الأوامر السرية',
    roundLabel: 'الجولة',
    aliveSuffix: 'أحياء',
    roleWas: 'كان دوره',
    rolesDmNote: 'تم توزيع الأدوار سراً عبر الرسائل الخاصة',
    write: 'اكتب',
    toJoin: 'للانضمام',
    minimum: 'الحد الأدنى',
    hostFeedTitle: 'الرسائل الخاصة — المشرف فقط',
  },
  messages: {
    roleReveal: (role: string, desc: string) => `دورك: ${role}. ${desc}`,
    mafiaTeammates: (names: string) => `زملاؤك في المافيا: ${names}`,
    nightActionRecorded: (action: string, target: string) => `تم تسجيل إجراءك: ${action} ${target}`,
    investigationResult: (target: string, isMafia: boolean) => `نتيجة التحقيق: ${target} ${isMafia ? 'مافيا' : 'ليس مافيا'}.`,
    nightResultProtected: (name: string) => `تم حماية ${name} من قبل الطبيب!`,
    nightResultEliminated: (name: string) => `تم إقصاء ${name} خلال الليل!`,
    dayEliminated: (name: string) => `تم استبعاد ${name} خلال الليل.`,
    dayNoEliminated: 'لم يتم استبعاد أي لاعب خلال الليل.',
    voteRecorded: (name: string) => `تم تسجيل تصويتك لـ ${name}.`,
    voteResult: (name: string) => `تم إقصاء ${name} بالتصويت!`,
    voteTie: 'تعادل في الأصوات! لم يتم إقصاء أحد.',
    mafiaWin: 'فاز فريق المافيا!',
    citizensWin: 'فاز فريق المواطنين!',
    notEnoughPlayers: (count: number, required: number) => `لاعبون غير كافيين: ${count}/${required}`,
    gameFull: 'اللعبة ممتلئة، لا يمكن الانضمام حالياً.',
    alreadyJoined: 'أنت منضم بالفعل للعبة.',
    invalidCommand: 'أمر غير صحيح أو هدف غير صالح. تأكد من الصيغة والهدف.',
    alreadyActed: 'لقد قمت بإجراء ليلي بالفعل.',
    alreadyVoted: 'لقد صوتت بالفعل في هذه الجولة.',
    notFound: 'لم يتم العثور على اللاعب.',
    deadTarget: 'لا يمكنك التصويت للاعب ميت.',
    selfVote: 'لا يمكنك التصويت لنفسك.',
    votingNotStarted: 'مرحلة التصويت لم تبدأ بعد.',
    alreadyJoinedGame: 'أنت منضم بالفعل للعبة.',
    phaseNotPlaying: 'اللعبة ليست في مرحلة اللعب.',
    discussTitle: 'ناقشوا مع اللاعبين',
    discussBody: 'ناقشوا مع اللاعبين عبر YouTube Live Chat لتحديد من تصوتون ضده.',
    playersProgress: (count: number, required: number) => `${count} / ${required} لاعبين مطلوبين للبدء`,
    extraPlayersNeeded: (count: number) => `مطلوب ${count} لاعبون إضافيون للبدء`,
  },
};

export const ROLE_COLORS: Record<string, string> = {
  mafia: 'var(--neon-red)',
  doctor: 'var(--neon-green)',
  detective: 'var(--neon-cyan)',
  citizen: 'var(--border-color)',
};

export const PHASE_COLORS: Record<string, string> = {
  night: 'badge-pink',
  day: 'badge-yellow',
  voting: 'badge-yellow',
  gameOver: 'badge-purple',
  lobby: 'badge-cyan',
  idle: 'badge-cyan',
};